from typing import Any, Protocol


class DataConnectionProtocol(Protocol):
    def fetch_all(self, sql: str, params: dict[str, Any] | None = None) -> list[dict[str, Any]]: ...
    def fetch_one(self, sql: str, params: dict[str, Any] | None = None) -> dict[str, Any] | None: ...
    def execute(self, sql: str, params: dict[str, Any] | None = None) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
