from typing import Protocol
from models.customer import Customer
from schemas.customer import CustomerCreate


class CustomerRepositoryProtocol(Protocol):
    def get_all(self, skip: int = 0, limit: int = 25, region: str | None = None, sort_by: str | None = None, sort_order: str = "asc") -> list[Customer]: ...
    def count(self, region: str | None = None) -> int: ...
    def get_by_id(self, id: int) -> Customer | None: ...
    def create(self, data: CustomerCreate) -> Customer: ...
    def export_all(self) -> tuple[list[str], list]: ...
