from typing import Protocol

from models.job import Job


class JobRepositoryProtocol(Protocol):
    def create(self, job_id: str, name: str, payload: dict) -> Job: ...
    def get(self, job_id: str) -> Job | None: ...
    def list(self, skip: int, limit: int) -> list[Job]: ...
    def set_running(self, job_id: str) -> None: ...
    def set_success(self, job_id: str, result: dict) -> None: ...
    def set_failed(self, job_id: str, error: str) -> None: ...
