from typing import Protocol

from models.product import Product
from schemas.product import ProductCreate


class ProductRepositoryProtocol(Protocol):
    def get_all(
        self, skip: int = 0, limit: int = 25, category: str | None = None,
        sort_by: str | None = None, sort_order: str = "asc",
    ) -> list[Product]: ...
    def count(self, category: str | None = None) -> int: ...
    def get_by_id(self, id: int) -> Product | None: ...
    def create(self, data: ProductCreate) -> Product: ...
    def export_all(self) -> tuple[list[str], list]: ...
