from typing import Protocol

from schemas.reports import LowStockRow, MonthlyRevenueRow, SalesByRegionRow, SummaryRow


class ReportsRepositoryProtocol(Protocol):
    def sales_by_region(self) -> list[SalesByRegionRow]: ...
    def monthly_revenue(self, year: int | None = None) -> list[MonthlyRevenueRow]: ...
    def low_stock(self) -> list[LowStockRow]: ...
    def summary(self) -> SummaryRow: ...
