from typing import Protocol

from schemas.reports import (
    LowStockRow,
    MonthlyRevenueRow,
    SalesByRegionRow,
    StockAlertRow,
    StockHealthRow,
    StockProjectionRow,
    SummaryRow,
)


class ReportsRepositoryProtocol(Protocol):
    def sales_by_region(self) -> list[SalesByRegionRow]: ...
    def monthly_revenue(self, year: int | None = None) -> list[MonthlyRevenueRow]: ...
    def low_stock(self) -> list[LowStockRow]: ...
    def stock_health(self, limit: int = 10) -> list[StockHealthRow]: ...
    def stock_alerts(self, limit: int = 10) -> list[StockAlertRow]: ...
    def stock_projections(self) -> list[StockProjectionRow]: ...
    def summary(self) -> SummaryRow: ...
